Add license and code of conduct
ALPHAVIO/ToDoist pull request #6
Opened 2021-01-18 17:57 UTC by tanvimoharir

This has the MIT license only(was initially trying to add both the files onto the same branch)

2021-01-18 20:10 UTC, Pranav016 requested changes

2021-01-18 20:10 UTC, Pranav016 commented on LICENSE.md
> +Copyright (c) 2021 Pranav016
Change `Pranav016` to `Pranav016 & ALPHAVIO organization`

2021-01-18 20:12 UTC, Pranav016 commented
I'd recommend you to `squash` your commits for this pull request since you'll be having 3 commits that will be doing the same thing. So squashing all the 3 commits would make sense. Squash them and change their commit message to `Add LICENSE.md`.
Let me know if you face any difficulty.

2021-01-19 17:31 UTC, tanvimoharir commented on LICENSE.md
> +Copyright (c) 2021 Pranav016
This is done.

2021-01-19 17:33 UTC, tanvimoharir commented
@Pranav016  I have not squashed any commits before this and I tried to do this on some commits on my private repository,however even after squashing I could still see all the commits.
I'm referred to :
https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc
Let me know if I'm missing something or otherwise.
Thanks!

2021-01-19 17:33 UTC, Pranav016 approved these changes

2021-01-19 17:35 UTC, Pranav016 commented
@tanvimoharir Great ,now please squash your commits. There are 3 commits that are trying to do the same thing, so we don't want the other two irrelevant commits in the commit history. You can refer to the documentation or a tutorial for squashing, isn't very hard.

2021-01-19 17:41 UTC, Pranav016 commented
> @Pranav016 I have not squashed any commits before this and I tried to do this on some commits on my private repository,however even after squashing I could still see all the commits.
> I referred to :
> https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc
> Let me know if I'm missing something or otherwise.
> Thanks!

I think this article is correct to some extent but it has missed some small steps that is why you are commits are still visible.
Here are the steps-
```
git rebase -i HEAD~3
```
Now your vim will open up. Press `i` to enter editor mode.
Now let one of the commits remain as `pick` and replace other two picks with `squash` and press `Esc ` and then type ` : wq`.
A new window will open up, press `i` to edit. Then just place `#` in front of the commit messages that are not needed. (Any two)
Retain the commit message that is more relevant.
then press `Esc ` and then type ` : wq`.

That will do the job. These are all the steps easily explained.

2021-01-19 18:12 UTC, tanvimoharir commented
@Pranav016 Thanks for the steps. I had followed the same but I thought that the squashed commits won't be visible( as per the link I shared above its supposed to edit git history).
Regardless, I have done the above mentioned steps, Please check and let me know. Thanks again.

2021-01-20 05:15 UTC, closed without merging