Create CODE_OF_CONDUCT.md
ALPHAVIO/ToDoist pull request #7
Opened 2021-01-18 17:57 UTC by tanvimoharir

CODE_OF_CONDUCT file

2021-01-18 20:21 UTC, Pranav016 requested changes
Also, squash your commits after working on the requested changes. Then you can force push to this branch.

2021-01-18 20:21 UTC, Pranav016 commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at pranavmendi@gmail.com. All
use markdown and hide the email. (create a hyperlink that leads straight to the mail)
```
[Email](mailto:pranavmendi@gmail.com)
```

2021-01-19 17:56 UTC, tanvimoharir commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at pranavmendi@gmail.com. All
This is changed.

2021-01-19 18:22 UTC, tanvimoharir commented
@Pranav016  Please let me know in case of further changes or otherwise. Thanks.

2021-01-19 20:20 UTC, Pranav016 commented
> @Pranav016 Please let me know in case of further changes or otherwise. Thanks.

They are almost ready to be merged but I think you have increased your commits even more. (I have make sure the commit history stays clean) Its fine you are not able to squash but I'd recommend to make a new pull request with these files with just a single commit. That'll be great.

![image](https://user-images.githubusercontent.com/54665036/105088299-b3671f80-5ac1-11eb-9393-018feacb42e7.png)

2021-01-20 04:54 UTC, closed without merging