Adding CODE_OF_CONDUCT.md
ALPHAVIO/ToDoist pull request #8
Opened 2021-01-20 05:12 UTC by tanvimoharir

2021-01-20 13:17 UTC, Pranav016 requested changes
A couple of changes required to remove exposed links.

2021-01-20 13:17 UTC, Pranav016 commented on CODE_OF_CONDUCT.md
> +available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
Turn the link to a hyper link just like you did to the email.
Open links don't look good.

2021-01-20 13:17 UTC, Pranav016 commented on CODE_OF_CONDUCT.md
> +https://www.contributor-covenant.org/faq
Make this a hyper link.
Example
```
[Contributor Convent FAQ](https://www.contributor-covenant.org/faq)
```

2021-01-20 13:17 UTC, Pranav016 commented on CODE_OF_CONDUCT.md
> +threatening, offensive, or harmful.
Turn these 2 into bullet points.

2021-01-21 04:38 UTC, tanvimoharir commented on CODE_OF_CONDUCT.md
> +threatening, offensive, or harmful.
Changed.

2021-01-21 04:39 UTC, tanvimoharir commented on CODE_OF_CONDUCT.md
> +https://www.contributor-covenant.org/faq
This is done.

2021-01-21 04:39 UTC, tanvimoharir commented on CODE_OF_CONDUCT.md
> +available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html
This is done.

2021-01-21 10:41 UTC, Pranav016 approved these changes

2021-01-21 10:41 UTC, merged